# Generated by Django 4.2.10 on 2025-04-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(choices=[('appointments', 'Appointments'), ('revenue', 'Revenue'), ('staff_performance', 'Staff Performance'), ('client_activity', 'Client Activity'), ('services', 'Services')], max_length=50, verbose_name='Type')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/', verbose_name='File')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=10, verbose_name='Format')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=50, verbose_name='Action')),
                ('entity_type', models.CharField(blank=True, choices=[('appointment', 'Appointment'), ('service', 'Service'), ('user', 'User'), ('category', 'Category'), ('report', 'Report')], max_length=50, null=True, verbose_name='Entity type')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='Entity ID')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Details')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'User Log',
                'verbose_name_plural': 'User Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
