# Generated by Django 4.2.10 on 2025-04-24 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='admin_panel.report', verbose_name='Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['user'], name='admin_panel_user_id_a25932_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['action'], name='admin_panel_action_2ce0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['created_at'], name='admin_panel_created_a2aa93_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['report'], name='admin_panel_report__5ce06c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['type'], name='admin_panel_type_32c041_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by'], name='admin_panel_created_7c655f_idx'),
        ),
    ]
